#https://pub.dev/packages/flutter_lints
include: package:flutter_lints/flutter.yaml

linter:

  rules:
    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
  
  errors:
    invalid_annotation_target: ignore
    invalid_use_of_visible_for_testing_member: error
