name: CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  analyze_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      # ref: https://github.com/marketplace/actions/flutter-action
      - name: checkout source code
        uses: actions/checkout@v3

      # https://github.com/kuhnroyal/flutter-fvm-config-action
      - name: Fetch flutter config
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: install flutter
        uses: subosito/flutter-action@v2

        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: ${{ env.FLUTTER_VERSION }}-${{ env.FLUTTER_CHANNEL }}

      # 依存関係読み込み
      - name: get dependencies
        run: flutter pub get

      # インポートが整列されているかチェック
      - name: check import sort
        run: flutter pub run import_sorter:main --no-comments --exit-if-changed

      # コードのフォーマットチェック
      - name: check code format
        run: dart format --set-exit-if-changed .

      # freezed等のファイル生成
      - name: generate codes with build_runner
        run: flutter pub run build_runner build -d

      # analyzeに引っ掛かるかチェック
      - name: check analyze
        run: flutter analyze

      # テストを通過するかチェック
      - name: test
        run: flutter test