name: iOS Build

on:
  push:
    tags:
      - "*.*.*"
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      # ref: https://github.com/marketplace/actions/flutter-action
      - name: checkout source code
        uses: actions/checkout@v3

      # https://github.com/kuhnroyal/flutter-fvm-config-action
      - name: Fetch flutter config
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: install flutter
        uses: subosito/flutter-action@v2

        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
          cache-key: ${{ env.FLUTTER_VERSION }}-${{ env.FLUTTER_CHANNEL }}

      - name: get dependencies
        run: flutter pub get

      - name: generate codes with build_runner
        run: flutter pub run build_runner build

      # iOS Build
      - run: flutter build ios --release --no-codesign
      # 成果物アップロード
      - name: artifact upload
        uses: actions/upload-artifact@v3
        with:
          # 保存ファイル名（name.zip）
          name: ios
          # 保存するファイル
          path: ./build/ios/
          # 保存期間（日）
          retention-days: 1